# Generated by Django 4.2.7 on 2023-12-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('credit', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('availability', models.BooleanField()),
                ('course', models.ManyToManyField(related_name='modules', to='auth.group')),
            ],
        ),
    ]
