# Generated by Django 4.2.7 on 2023-12-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='courses',
        ),
    ]
