# Generated by Django 4.2.7 on 2023-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='availability',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default='Elective', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='55-1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.CharField(default=20, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
