# Generated by Django 4.2.7 on 2023-12-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesreg', '0002_module_availability_module_category_module_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
