# Generated by Django 4.2.7 on 2023-12-22 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_rename_course_module_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_alter_registration_module_alter_registration_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('module', 'student')},
        ),
    ]
